# Generated by Django 4.0.5 on 2022-06-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastrest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp_details',
            old_name='f_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='emp_details',
            name='emp_id',
        ),
        migrations.RemoveField(
            model_name='emp_details',
            name='l_name',
        ),
        migrations.AddField(
            model_name='emp_details',
            name='latitude',
            field=models.FloatField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emp_details',
            name='longitude',
            field=models.FloatField(default=0, max_length=180),
            preserve_default=False,
        ),
    ]
